---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ai-platform.suse.com
  resources:
  - installaiextensions
  - settings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ai-platform.suse.com
  resources:
  - installaiextensions/finalizers
  verbs:
  - update
- apiGroups:
  - ai-platform.suse.com
  resources:
  - installaiextensions/status
  - settings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
- apiGroups:
  - catalog.cattle.io
  resources:
  - clusterrepos
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - catalog.cattle.io
  resources:
  - clusterrepos/status
  verbs:
  - get
  - patch
  - update
