annotations:
  licenses: Apache-2.0
  helm.sh/images: |
    - image: ghcr.io/suse/aif-ui:2.2.0-dev.3
      name: aif-ui
apiVersion: v2
name: aif-ui
version: 2.2.0-dev.3
description: SUSE AI Rancher UI Extension
type: application
keywords:
  - rancher
  - extension
  - ai
home: https://github.com/SUSE/aif
icon: https://raw.githubusercontent.com/SUSE/aif/main/pkg/aif-ui/assets/logo.svg
sources:
  - https://github.com/SUSE/aif
appVersion: 2.2.0-dev.3
maintainers:
  - url: https://www.suse.com/
    name: SUSE LLC
