apiVersion: ai.suse.com/v1alpha1
kind: InstallAIExtension
metadata:
  name: aif-ui
spec:
  source:
    kind: Helm
    helm:
      chartURL: "oci://ghcr.io/suse/chart/suse-ai-lifecycle-manager"
      version: "1.1.0"
  extension:
    name: suse-ai-lifecycle-manager
    version: "1.1.0"
