annotations:
  helm.sh/images: |
    - image: ghcr.io/leomiraanda/aif-operator:0.2.0
      name: aif-operator
apiVersion: v2
name: aif-operator
version: 0.2.0
description: SUSE AI Operator
type: application
home: https://github.com/SUSE/aif
icon: https://raw.githubusercontent.com/SUSE/aif/main/pkg/aif-ui/assets/logo.svg
sources:
  - https://github.com/SUSE/aif
appVersion: 0.2.0
maintainers:
  - url: https://www.suse.com/
    name: SUSE LLC
keywords:
  - rancher
  - extension
  - ai
  - kubernetes
  - operator
