global:
  imageRegistry: ""
  imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

imagePullSecrets: []

image:
  registry: ""
  repository: nginx
  tag: "latest"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  port: 80
  type: ClusterIP

gpu:
  enabled: false
  count: "1"
  type: nvidia.com/gpu

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

livenessProbe: {}
readinessProbe: {}

env: []
ports: []

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false

nodeSelector: {}
tolerations: []
affinity: {}
podAnnotations: {}

extraVolumes: []
extraVolumeMounts: []

priorityClassName: ""

